#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "site" / "data"

QUESTION_FILES = sorted(
    path for path in DATA_DIR.glob("interview-*-questions.json") if not path.name.endswith("-vi.json")
)

CATEGORY_MAP = {
    "Python Core": "Python Cốt lõi",
    "Python Application": "Ứng dụng Python",
    "API Design": "Thiết kế API",
    "Files and JSON": "File và JSON",
    "Testing": "Kiểm thử",
    "Logging": "Logging",
    "CLI": "CLI",
    "HTTP APIs": "HTTP API",
    "Databases": "Database",
    "Automation": "Tự động hóa",
    "Performance": "Hiệu năng",
    "AI/ML": "AI/ML",
    "Project Delivery": "Triển khai dự án",
    "Backend": "Backend",
    "System Design": "Thiết kế hệ thống",
    "Distributed Systems": "Hệ thống phân tán",
    "Reliability": "Reliability",
    "Observability": "Quan sát hệ thống",
    "Security": "Bảo mật",
    "Data Engineering": "Kỹ thuật dữ liệu",
    "Architecture": "Kiến trúc",
}

LEVEL_MAP = {
    "Basic": "Cơ bản",
    "Intermediate": "Trung cấp",
    "Advanced": "Nâng cao",
    "basic": "cơ bản",
    "intermediate": "trung cấp",
    "advanced": "nâng cao",
}

TITLE_MAP = {
    "Basic Master Interview Question Bank": "Ngân Hàng Câu Hỏi Phỏng Vấn Master Cơ Bản",
    "Intermediate Master Interview Question Bank": "Ngân Hàng Câu Hỏi Phỏng Vấn Master Trung Cấp",
    "Advanced Master Interview Question Bank": "Ngân Hàng Câu Hỏi Phỏng Vấn Master Nâng Cao",
    "Automation Interview Question Bank": "Ngân Hàng Câu Hỏi Phỏng Vấn Về Tự Động Hóa",
    "Backend Interview Question Bank": "Ngân Hàng Câu Hỏi Phỏng Vấn Backend",
    "AI and Machine Learning Interview Question Bank": "Ngân Hàng Câu Hỏi Phỏng Vấn AI Và Machine Learning",
    "System Design Interview Question Bank": "Ngân Hàng Câu Hỏi Phỏng Vấn Thiết Kế Hệ Thống",
    "Fresher Interview Question Bank": "Ngân Hàng Câu Hỏi Phỏng Vấn Fresher",
    "Mid-Level Interview Question Bank": "Ngân Hàng Câu Hỏi Phỏng Vấn Trung Cấp",
    "Senior Interview Question Bank": "Ngân Hàng Câu Hỏi Phỏng Vấn Senior",
    "Bilingual VI/EN Interview Question Bank": "Ngân Hàng Câu Hỏi Phỏng Vấn Song Ngữ VI/EN",
}

SUBTITLE_MAP = {
    "More than 100 beginner-to-strong-junior questions for Python, scripting, files, testing, APIs, automation, and entry-level AI concepts.": "Hơn 100 câu hỏi từ mức mới bắt đầu đến junior vững về Python, scripting, file, testing, API, automation và các khái niệm AI đầu vào.",
    "Mid-level interview questions for Python application engineering, APIs, databases, async, automation, testing, and data processing.": "Bộ câu hỏi phỏng vấn trung cấp cho phát triển ứng dụng Python, API, database, async, automation, testing và xử lý dữ liệu.",
    "More than 100 advanced questions covering concurrency, APIs, data systems, resilience, observability, AI platforms, and production delivery.": "Hơn 100 câu hỏi nâng cao về concurrency, API, hệ dữ liệu, resilience, observability, nền tảng AI và triển khai production.",
    "Intermediate scripting and automation questions focused on practical repeatable workflows.": "Bộ câu hỏi trung cấp về scripting và automation, tập trung vào workflow thực tế có thể lặp lại.",
    "Intermediate backend questions about APIs, persistence, validation, and reliability.": "Bộ câu hỏi backend trung cấp về API, lưu trữ, validation và reliability.",
    "Advanced question set covering model evaluation, retrieval, prompting, and production AI concerns.": "Bộ câu hỏi nâng cao về đánh giá model, retrieval, prompting và các vấn đề AI trong production.",
    "Advanced distributed systems and delivery questions for backend and platform interviews.": "Bộ câu hỏi nâng cao về hệ thống phân tán và delivery cho phỏng vấn backend và platform.",
    "Synthesized fresher-level interview quiz with conceptual questions, small traps, and simple code reasoning.": "Bộ quiz phỏng vấn mức fresher gồm câu hỏi khái niệm, bẫy nhỏ và suy luận code đơn giản.",
    "Synthesized intermediate interview quiz focused on implementation tradeoffs, debugging, optimization, APIs, automation, and persistence.": "Bộ quiz phỏng vấn trung cấp tập trung vào trade-off triển khai, debug, tối ưu, API, automation và persistence.",
    "Hard senior-level interview quiz focused on design tradeoffs, scaling, reliability, operations, distributed systems, and AI platform decisions.": "Bộ quiz phỏng vấn senior khó, tập trung vào trade-off thiết kế, scaling, reliability, vận hành, hệ phân tán và quyết định nền tảng AI.",
    "Vietnamese and English interview prompts for learning, self-study, and GitHub Pages search.": "Bộ câu hỏi phỏng vấn tiếng Việt và tiếng Anh để học thuật ngữ, tự học và tìm kiếm trên GitHub Pages.",
}

REPLACEMENTS = [
    ("A. ", ""),
    ("An. ", ""),
    ("because ", "bởi vì "),
    ("Because ", "Bởi vì "),
    ("Use a ", "Dùng "),
    ("Use an ", "Dùng "),
    ("Use ", "Dùng "),
    ("Choose a ", "Hãy chọn "),
    ("Choose an ", "Hãy chọn "),
    ("Choose ", "Hãy chọn "),
    ("It is ", "Nó là "),
    ("It helps ", "Nó giúp "),
    ("It keeps ", "Nó giữ "),
    ("It allows ", "Nó cho phép "),
    ("It limits ", "Nó giới hạn "),
    ("It runs ", "Nó chạy "),
    ("It rejects ", "Nó từ chối "),
    ("It stops ", "Nó tạm dừng "),
    ("They are ", "Chúng là "),
    ("They support ", "Chúng hỗ trợ "),
    ("They guarantee ", "Chúng đảm bảo "),
    ("This is ", "Điều này là "),
    ("This helps ", "Điều này giúp "),
    ("This matters ", "Điều này quan trọng "),
    ("This improves ", "Điều này cải thiện "),
    ("This reduces ", "Điều này giảm "),
    ("This makes ", "Điều này làm cho "),
    ("This prevents ", "Điều này ngăn "),
    ("Without ", "Nếu không có "),
    ("With ", "Với "),
    ("A list is mutable and a tuple is immutable.", "List là kiểu có thể thay đổi, còn tuple là kiểu bất biến."),
    ("A callable that wraps another function or class to extend behavior.", "Một callable bọc quanh một hàm hoặc class khác để mở rộng hành vi."),
    ("A function that remembers variables from its enclosing scope.", "Một hàm ghi nhớ các biến từ scope bao quanh của nó."),
    ("An object is iterable when it can return an iterator, and an iterator yields items until exhaustion.", "Một object là iterable khi nó có thể trả về một iterator, và iterator đó trả ra các phần tử cho đến khi hết."),
    ("The Global Interpreter Lock is a CPython mechanism that affects how Python threads execute bytecode.", "Global Interpreter Lock là một cơ chế của CPython ảnh hưởng đến cách các luồng Python thực thi bytecode."),
    ("The scheduler that manages coroutine execution and I/O readiness in async programs.", "Bộ lập lịch quản lý việc thực thi coroutine và trạng thái sẵn sàng I/O trong các chương trình async."),
    ("It runs multiple awaitables concurrently and collects their results.", "Nó chạy nhiều awaitable đồng thời và thu thập kết quả của chúng."),
    ("It limits how many tasks can enter a critical or expensive section at once.", "Nó giới hạn số lượng tác vụ có thể đi vào một vùng tới hạn hoặc tốn kém cùng một lúc."),
    ("They guarantee setup and cleanup around a block of code.", "Chúng đảm bảo việc khởi tạo và dọn dẹp quanh một khối code."),
    ("They support lazy processing and lower memory use.", "Chúng hỗ trợ xử lý lười và giảm sử dụng bộ nhớ."),
    ("When tasks spend a lot of time waiting on I/O.", "Khi các tác vụ dành nhiều thời gian để chờ I/O."),
    ("When the work is CPU-bound and can benefit from multiple processes.", "Khi công việc bị ràng buộc bởi CPU và có thể hưởng lợi từ nhiều tiến trình."),
    ("It allows one thread to manage many waiting tasks efficiently.", "Nó cho phép một luồng quản lý nhiều tác vụ đang chờ một cách hiệu quả."),
    ("A list ", "List "),
    ("A tuple ", "Tuple "),
    ("A dictionary ", "Dictionary "),
    ("A set ", "Set "),
    ("A transaction ", "Transaction "),
    ("A queue ", "Queue "),
    ("A release strategy ", "Chiến lược phát hành "),
    ("A strategy ", "Một chiến lược "),
    ("A copy of the primary database used mainly to serve read traffic.", "Một bản sao của database chính, chủ yếu dùng để phục vụ lưu lượng đọc."),
    ("A shared identifier used to follow one request across multiple components.", "Một định danh dùng chung để theo dõi một request qua nhiều thành phần."),
    ("A bug where behavior depends on unpredictable timing between concurrent operations.", "Một lỗi mà hành vi phụ thuộc vào thời điểm không thể dự đoán giữa các thao tác đồng thời."),
    ("A way to slow producers when consumers cannot keep up.", "Một cách làm chậm bên sản xuất khi bên tiêu thụ không theo kịp."),
    ("A mechanism that restricts how many requests a client can make over time.", "Một cơ chế giới hạn số lượng request mà client có thể gửi trong một khoảng thời gian."),
    ("A client-supplied or generated key used to prevent duplicate handling of the same request.", "Một khóa do client cung cấp hoặc hệ thống sinh ra để ngăn xử lý trùng lặp cùng một request."),
    ("A pattern for coordinating multi-step distributed workflows with compensating actions.", "Một mẫu để điều phối workflow phân tán nhiều bước với các hành động bù trừ."),
    ("It gives both the index and the item.", "Nó cung cấp cả chỉ số lẫn phần tử."),
    ("It avoids manual counters and makes loops more readable.", "Nó tránh phải tự đếm thủ công và giúp vòng lặp dễ đọc hơn."),
    ("It represents the sequence 0, 1, 2, 3, 4.", "Nó biểu diễn dãy 0, 1, 2, 3, 4."),
    ("It collects extra positional arguments into a tuple.", "Nó gom các positional argument bổ sung vào một tuple."),
    ("It collects extra keyword arguments into a dictionary.", "Nó gom các keyword argument bổ sung vào một dictionary."),
    ("A compact way to build a list from an iterable with optional filtering.", "Một cách viết gọn để tạo list từ iterable, có thể kèm điều kiện lọc."),
    ("A compact way to build a dictionary from an iterable.", "Một cách viết gọn để tạo dictionary từ iterable."),
    ("A small anonymous function expression.", "Một biểu thức hàm ẩn danh nhỏ gọn."),
    ("It exits the loop immediately.", "Nó thoát khỏi vòng lặp ngay lập tức."),
    ("It skips the rest of the current iteration and moves to the next one.", "Nó bỏ qua phần còn lại của lượt lặp hiện tại và chuyển sang lượt kế tiếp."),
    ("It does nothing and is used as a placeholder.", "Nó không làm gì cả và thường được dùng làm chỗ giữ chỗ."),
    ("None means no value, while an empty string is still a real string value.", "None nghĩa là không có giá trị, còn chuỗi rỗng vẫn là một giá trị string thực sự."),
    ("`is` checks identity and `==` checks value equality.", "`is` kiểm tra danh tính đối tượng, còn `==` kiểm tra giá trị bằng nhau."),
    ("Repeated requests with the same intent produce the same final effect.", "Các request lặp lại với cùng ý định sẽ tạo ra cùng một kết quả cuối cùng."),
    ("Because dependencies should be reproducible across environments.", "Bởi vì dependency cần có khả năng tái lập giữa các môi trường."),
    ("Because clear operational instructions reduce setup friction and mistakes.", "Bởi vì hướng dẫn vận hành rõ ràng giúp giảm ma sát khi setup và hạn chế sai sót."),
    ("Because the same object is reused across function calls.", "Bởi vì cùng một object được tái sử dụng qua nhiều lần gọi hàm."),
    ("Because the default object is reused across function calls.", "Bởi vì object mặc định được tái sử dụng qua nhiều lần gọi hàm."),
    ("Because smaller modules improve navigation, ownership, and change isolation.", "Bởi vì module nhỏ hơn giúp điều hướng tốt hơn, rõ ownership hơn và cô lập thay đổi tốt hơn."),
    ("Keeping responsibilities like transport, domain logic, and persistence distinct.", "Giữ cho các trách nhiệm như transport, logic nghiệp vụ và persistence tách biệt với nhau."),
    ("Passing dependencies into code instead of hardcoding them internally.", "Truyền dependency vào code thay vì hardcode chúng ở bên trong."),
    ("Because reusable functions are easier to test and reuse from other entrypoints.", "Bởi vì các hàm tái sử dụng sẽ dễ test hơn và có thể dùng lại từ các entrypoint khác."),
    ("Because failures need different control flow from successful responses.", "Bởi vì các tình huống lỗi cần luồng xử lý khác với response thành công."),
    ("Because invalid requests should be rejected before they contaminate business logic.", "Bởi vì các request không hợp lệ nên bị từ chối trước khi làm bẩn logic nghiệp vụ."),
    ("Because related changes should succeed or fail together.", "Bởi vì các thay đổi liên quan cần cùng thành công hoặc cùng thất bại."),
    ("Because one write can succeed while the other fails, causing inconsistency.", "Bởi vì một lần ghi có thể thành công còn lần kia thất bại, gây ra trạng thái không nhất quán."),
    ("Because many delivery systems are effectively at-least-once in real operations.", "Bởi vì nhiều hệ thống giao nhận trong thực tế vận hành theo kiểu at-least-once."),
    ("Because long waits can tie up resources and worsen system-wide instability.", "Bởi vì chờ quá lâu có thể chiếm tài nguyên và làm sự bất ổn toàn hệ thống tệ hơn."),
    ("Because timeout choices affect success rate, user experience, and resource usage together.", "Bởi vì việc chọn timeout ảnh hưởng đồng thời đến tỷ lệ thành công, trải nghiệm người dùng và mức sử dụng tài nguyên."),
    ("Because the process may be alive but not actually ready to serve traffic safely.", "Bởi vì process có thể còn sống nhưng chưa thực sự sẵn sàng phục vụ traffic một cách an toàn."),
    ("Because safe change strategy matters as much as initial deployment strategy.", "Bởi vì chiến lược thay đổi an toàn quan trọng ngang với chiến lược triển khai ban đầu."),
    ("Because failed releases need a fast and safe recovery path.", "Bởi vì một bản phát hành lỗi cần có đường lui nhanh và an toàn."),
    ("Because it previews actions without changing real data.", "Bởi vì nó cho phép xem trước hành động mà không thay đổi dữ liệu thật."),
    ("Because the related data is known to be needed and eager loading avoids repeated extra queries.", "Bởi vì dữ liệu liên quan được biết trước là cần thiết và eager loading tránh được các truy vấn phụ lặp lại."),
    ("Because retries or overlapping runs happen in real operations.", "Bởi vì retry hoặc các lần chạy chồng lấn là chuyện xảy ra trong vận hành thực tế."),
    ("Because repeated open-close operations add unnecessary I/O overhead.", "Bởi vì việc mở rồi đóng lặp lại gây thêm overhead I/O không cần thiết."),
    ("Measure bottlenecks first.", "Hãy đo bottleneck trước."),
    ("Line-by-line iteration is usually more memory-efficient.", "Việc lặp từng dòng thường tiết kiệm bộ nhớ hơn."),
    ("Collecting pieces and using `join()` is usually better.", "Việc gom các phần rồi dùng `join()` thường tốt hơn."),
    ("A set is usually better for repeated membership checks.", "Set thường tốt hơn cho các phép kiểm tra membership lặp lại."),
    ("A set is usually faster for repeated membership checks.", "Set thường nhanh hơn cho các phép kiểm tra membership lặp lại."),
    ("Use `==` for normal value comparison and `is` mainly for identity checks like `x is None`.", "Dùng `==` để so sánh giá trị thông thường và dùng `is` chủ yếu cho các phép kiểm tra identity như `x is None`."),
    ("Because it closes the file automatically even if an error occurs.", "Bởi vì nó tự động đóng file ngay cả khi có lỗi xảy ra."),
    ("It returns the value for key `x` or `0` if the key is missing.", "Nó trả về giá trị của key `x` hoặc `0` nếu key không tồn tại."),
    ("To store key-value mappings for fast lookup by key.", "Để lưu các cặp key-value cho phép tra cứu nhanh bằng key."),
    ("It gives both the index and item during iteration.", "Nó cung cấp cả chỉ số và phần tử trong khi lặp."),
    ("The context manager handles cleanup safely.", "Context manager xử lý phần dọn dẹp một cách an toàn."),
    ("Use a set when you need unique values or fast membership checks.", "Dùng set khi bạn cần các giá trị duy nhất hoặc cần kiểm tra membership nhanh."),
    ("What does slicing do in Python?", "Slicing trong Python dùng để làm gì?"),
    ("What does truthy or falsy mean in Python?", "Truthy hoặc falsy trong Python có nghĩa là gì?"),
    ("What is the difference between a list and a tuple in Python?", "Sự khác nhau giữa list và tuple trong Python là gì?"),
    ("What is the difference between `==` and `is` in Python?", "Sự khác nhau giữa `==` và `is` trong Python là gì?"),
    ("Why is `if __name__ == '__main__':` used?", "Vì sao dùng `if __name__ == '__main__':`?"),
    ("Why is `super()` used?", "Vì sao dùng `super()`?"),
    ("Why are mutable default arguments dangerous?", "Vì sao tham số mặc định có thể thay đổi lại nguy hiểm?"),
    ("Why is it okay to clarify assumptions in an interview question?", "Vì sao việc làm rõ giả định trong câu hỏi phỏng vấn là chấp nhận được?"),
    ("Why is it good to say 'I am not sure, but here is how I would reason about it' in an interview?", "Vì sao nên nói 'Tôi chưa chắc, nhưng đây là cách tôi sẽ suy luận về vấn đề này' trong một buổi phỏng vấn?"),
    ("Why should ORM queries still be inspected for performance?", "Vì sao vẫn nên kiểm tra hiệu năng của các query ORM?"),
    ("Why can ORM convenience still require SQL knowledge?", "Vì sao sự tiện lợi của ORM vẫn đòi hỏi kiến thức SQL?"),
    ("Why can integration tests still be valuable even if unit tests exist?", "Vì sao integration test vẫn có giá trị ngay cả khi đã có unit test?"),
    ("Why is batching useful when calling external services?", "Vì sao batching hữu ích khi gọi các dịch vụ bên ngoài?"),
    ("Why can concurrency limits matter in async systems?", "Vì sao giới hạn concurrency lại quan trọng trong các hệ thống async?"),
    ("Why can server-side defaults be useful in APIs?", "Vì sao default ở phía server có thể hữu ích trong API?"),
    ("Why are flaky tests dangerous?", "Vì sao flaky test lại nguy hiểm?"),
    ("Why is parametrized testing useful when validating the same function across many inputs?", "Vì sao kiểm thử tham số hóa hữu ích khi kiểm tra cùng một hàm với nhiều input?"),
    ("Why must RAG still be evaluated carefully?", "Vì sao RAG vẫn phải được đánh giá cẩn thận?"),
    ("Why is feature leakage dangerous?", "Vì sao feature leakage lại nguy hiểm?"),
    ("Why can a monolith still be a good design?", "Vì sao monolith vẫn có thể là một thiết kế tốt?"),
    ("Why can a monolith still be a strong design choice?", "Vì sao monolith vẫn có thể là một lựa chọn thiết kế mạnh?"),
    ("Why can dynamic behavior in Python be powerful and dangerous at the same time?", "Vì sao hành vi động trong Python vừa mạnh mẽ vừa nguy hiểm cùng lúc?"),
    ("Why is a naive dual write to DB and broker dangerous?", "Vì sao dual write ngây thơ vào DB và broker lại nguy hiểm?"),
    ("Why can a readiness check that only returns process-up status still be misleading?", "Vì sao readiness check chỉ trả về trạng thái process đang chạy vẫn có thể gây hiểu lầm?"),
    ("What does `lru_cache` solve?", "`lru_cache` giải quyết vấn đề gì?"),
    ("What problem does the outbox pattern solve?", "Outbox pattern giải quyết vấn đề gì?"),
    ("What does a fallback provide?", "Fallback cung cấp điều gì?"),
    ("What does CORS control?", "CORS kiểm soát điều gì?"),
    ("What does RAG solve?", "RAG giải quyết vấn đề gì?"),
    ("What is a lambda in Python?", "Lambda trong Python là gì?"),
    ("What does `finally` guarantee?", "`finally` đảm bảo điều gì?"),
    ("What is a property in Python?", "Property trong Python là gì?"),
    ("What does `type(x)` show?", "`type(x)` cho biết điều gì?"),
    ("What does `items()` return for a dictionary?", "`items()` trả về gì cho một dictionary?"),
    ("What does `keys()` return for a dictionary?", "`keys()` trả về gì cho một dictionary?"),
    ("What does `values()` return for a dictionary?", "`values()` trả về gì cho một dictionary?"),
    ("What does it mean for a test to be flaky?", "Một test flaky có nghĩa là gì?"),
    ("What does `list[10:]` return when the list has only 6 elements?", "`list[10:]` trả về gì khi list chỉ có 6 phần tử?"),
    ("What does slicing do when the stop index exceeds the string or list length?", "Slicing làm gì khi chỉ số stop vượt quá độ dài của string hoặc list?"),
    ("What does HTTP 500 usually indicate?", "HTTP 500 thường chỉ ra điều gì?"),
    ("What does lazy loading trade off?", "Lazy loading đánh đổi điều gì?"),
    ("Why can timeouts still be needed in async code?", "Vì sao timeout vẫn có thể cần thiết trong code async?"),
    ("Why are strings immutable in Python?", "Vì sao string là bất biến trong Python?"),
    ("Why is explicit better than implicit in Python culture?", "Vì sao trong văn hóa Python, rõ ràng lại tốt hơn ngầm hiểu?"),
    ("When is CSV handling useful in Python labs and automations?", "Khi nào việc xử lý CSV hữu ích trong các lab và automation Python?"),
    ("When data is naturally key-value based and should be accessed by name or id.", "Khi dữ liệu vốn ở dạng key-value và nên được truy cập theo tên hoặc id."),
    ("A list or dict default is created once at function definition time, so later calls can see previous mutations.", "List hoặc dict mặc định chỉ được tạo một lần tại thời điểm định nghĩa hàm, nên các lần gọi sau có thể nhìn thấy các thay đổi trước đó."),
    ("The stop value is excluded, which is one of the most common off-by-one points in Python.", "Giá trị stop sẽ bị loại trừ, đây là một trong những lỗi lệch một đơn vị thường gặp nhất trong Python."),
    ("It prevents demo or CLI code from running automatically when the file is imported as a module.", "Nó ngăn code demo hoặc CLI tự động chạy khi file được import như một module."),
    ("Use it when the function should accept a variable number of positional values.", "Dùng nó khi hàm cần nhận một số lượng giá trị positional thay đổi."),
    ("It is useful for flexible configuration or passing named options through layers.", "Nó hữu ích cho cấu hình linh hoạt hoặc truyền các tùy chọn có tên qua nhiều tầng."),
    ("It replaces many simple `for` loops with a shorter expression that is still readable when kept simple.", "Nó thay thế nhiều vòng lặp `for` đơn giản bằng một biểu thức ngắn hơn nhưng vẫn dễ đọc nếu được giữ ở mức đơn giản."),
    ("It is useful when keys and values can be derived clearly in one expression.", "Nó hữu ích khi key và value có thể được suy ra rõ ràng trong một biểu thức."),
    ("Assigning multiple values from an iterable into separate variables.", "Gán nhiều giá trị từ một iterable vào các biến riêng biệt."),
    ("It improves readability in cases like `x, y = point` or swapping variables.", "Nó cải thiện khả năng đọc trong các trường hợp như `x, y = point` hoặc hoán đổi biến."),
    ("It returns part of a sequence using start, stop, and optional step.", "Nó trả về một phần của sequence bằng cách dùng start, stop và step tùy chọn."),
    ("It counts from the end of the sequence.", "Nó đếm từ cuối sequence."),
    ("For example, `items[-1]` gives the last element.", "Ví dụ, `items[-1]` sẽ trả về phần tử cuối cùng."),
    ("Some values evaluate to True or False in conditionals without being actual booleans.", "Một số giá trị được đánh giá là True hoặc False trong câu điều kiện mà không phải kiểu boolean thực sự."),
    ("Empty collections, zero, and `None` are falsy; most non-empty values are truthy.", "Collection rỗng, số 0 và `None` là falsy; còn hầu hết các giá trị không rỗng là truthy."),
    ("It turns a function into a generator that produces values lazily.", "Nó biến một hàm thành generator tạo ra các giá trị theo kiểu lười."),
    ("This is useful for streaming data rather than storing everything in memory first.", "Điều này hữu ích khi stream dữ liệu thay vì lưu toàn bộ vào bộ nhớ trước."),
    ("It removes whitespace or specified characters from both ends.", "Nó loại bỏ khoảng trắng hoặc các ký tự chỉ định ở cả hai đầu."),
    ("It is often used to clean user input or lines read from files.", "Nó thường được dùng để làm sạch input của người dùng hoặc các dòng đọc từ file."),
    ("When you need to break a string into pieces by separator.", "Khi bạn cần tách một chuỗi thành nhiều phần theo ký tự phân tách."),
    ("It is commonly used for CSV-like text, paths, and simple token parsing.", "Nó thường được dùng cho văn bản kiểu CSV, đường dẫn và việc parse token đơn giản."),
    ("When you need to combine multiple strings with a separator.", "Khi bạn cần ghép nhiều chuỗi bằng một ký tự phân tách."),
    ("It is more efficient and clearer than repeated string concatenation in loops.", "Nó hiệu quả hơn và rõ ràng hơn so với việc nối chuỗi lặp đi lặp lại trong vòng lặp."),
    ("It removes and returns an item, defaulting to the last one.", "Nó xóa và đồng thời trả về một phần tử, mặc định là phần tử cuối cùng."),
    ("It is useful when you need both the removed value and mutation.", "Nó hữu ích khi bạn cần cả giá trị bị xóa lẫn thao tác thay đổi dữ liệu."),
    ("When you need fast appends and pops from both ends.", "Khi bạn cần thêm và lấy phần tử nhanh ở cả hai đầu."),
    ("Lists are strong general-purpose sequences, but `deque` is better for queue-like workloads.", "List là sequence đa dụng tốt, nhưng `deque` phù hợp hơn với workload kiểu queue."),
    ("Maintaining a heap, often for getting the smallest item efficiently.", "Duy trì một heap, thường để lấy phần tử nhỏ nhất một cách hiệu quả."),
    ("It is useful for priority queues and top-k style tasks.", "Nó hữu ích cho priority queue và các bài toán kiểu top-k."),
    ("The requested resource was not found.", "Tài nguyên được yêu cầu không được tìm thấy."),
    ("It usually indicates a wrong path, missing entity, or missing endpoint.", "Nó thường cho thấy đường dẫn sai, thực thể không tồn tại hoặc endpoint bị thiếu."),
    ("It returns an empty list.", "Nó trả về một list rỗng."),
    ("Slicing beyond the end of a list does not raise IndexError the way direct indexing does.", "Việc slicing vượt quá cuối list không gây ra IndexError như khi truy cập trực tiếp bằng chỉ số."),
    ("It returns the available portion without raising an index error.", "Nó trả về phần có sẵn mà không gây lỗi index."),
    ("Slicing is more forgiving than direct indexing.", "Slicing dễ chịu hơn so với truy cập trực tiếp bằng chỉ số."),
    ("An internal server-side failure occurred while processing the request.", "Đã xảy ra lỗi phía server nội bộ trong khi xử lý request."),
    ("This is different from client-side mistakes such as 400 or 404.", "Điều này khác với các lỗi phía client như 400 hoặc 404."),
    ("A transaction groups operations so they succeed or fail together.", "Một transaction gom các thao tác lại để chúng cùng thành công hoặc cùng thất bại."),
    ("When durable event streams, replay, and consumer groups matter strongly.", "Khi event stream bền vững, khả năng replay và consumer group là các yếu tố đặc biệt quan trọng."),
    ("When flexible routing and traditional message queue patterns are needed.", "Khi cần routing linh hoạt và các mẫu message queue truyền thống."),
    ("To optimize read performance or simplify specific query patterns.", "Để tối ưu hiệu năng đọc hoặc đơn giản hóa các mẫu query cụ thể."),
    ("An alternative response or degraded behavior when a dependency is unavailable.", "Một response thay thế hoặc hành vi suy giảm khi dependency không khả dụng."),
    ("Which browser origins are allowed to access a server resource.", "Những origin nào của trình duyệt được phép truy cập một tài nguyên trên server."),
    ("It brings external retrieved context into generation instead of relying only on model memory.", "Nó đưa context được truy xuất từ bên ngoài vào quá trình sinh thay vì chỉ dựa vào bộ nhớ của model."),
    ("Queue depth, processing lag, or throughput pressure.", "Độ sâu queue, độ trễ xử lý hoặc áp lực thông lượng."),
    ("Average latency can hide severe tail behavior that users still experience.", "Độ trễ trung bình có thể che giấu các hành vi tail nghiêm trọng mà người dùng vẫn phải chịu."),
    ("Real upstream systems do not always deliver records in perfect time order.", "Các hệ thống upstream trong thực tế không phải lúc nào cũng gửi bản ghi theo đúng thứ tự thời gian hoàn hảo."),
    ("Slicing works on lists, strings, and tuples and is useful for extracting ranges cleanly.", "Slicing hoạt động trên list, string và tuple, và rất hữu ích để trích xuất các khoảng dữ liệu một cách gọn gàng."),
    ("Clarifying shows communication skill, not weakness.", "Việc làm rõ cho thấy kỹ năng giao tiếp, không phải điểm yếu."),
    ("Interviewers often care about the thinking process as much as the final answer.", "Người phỏng vấn thường quan tâm đến quá trình tư duy ngang với câu trả lời cuối cùng."),
    ("N+1 queries and excessive loading are common examples.", "N+1 query và việc tải quá nhiều dữ liệu là những ví dụ rất phổ biến."),
    ("Each test level catches different problems.", "Mỗi tầng kiểm thử sẽ phát hiện những loại vấn đề khác nhau."),
    ("Batch sizes still need tuning based on limits and memory.", "Kích thước batch vẫn cần được tinh chỉnh dựa trên giới hạn và bộ nhớ."),
    ("Async code needs backpressure just like other systems.", "Code async cũng cần backpressure giống như các hệ thống khác."),
    ("Good defaults simplify adoption while keeping behavior predictable.", "Default tốt giúp việc áp dụng đơn giản hơn mà vẫn giữ hành vi dễ dự đoán."),
    ("Good architecture does not remove the need for measurement.", "Kiến trúc tốt không loại bỏ nhu cầu phải đo lường."),
    ("Leakage creates false confidence and poor production performance.", "Leakage tạo ra sự tự tin sai lệch và làm hiệu năng production kém đi."),
    ("Microservices are not automatically better.", "Microservice không tự động tốt hơn."),
    ("Microservices are not automatically superior.", "Microservice không tự động vượt trội hơn."),
    ("Highly dynamic code is harder to reason about during debugging and review.", "Code quá động sẽ khó suy luận hơn trong quá trình debug và review."),
    ("Continuing to offer reduced functionality instead of total failure.", "Tiếp tục cung cấp chức năng ở mức suy giảm thay vì sập hoàn toàn."),
    ("You still need to understand joins, indexes, and query shape. Otherwise, an ORM can hide slow N+1 queries or pull much more data than needed.", "Bạn vẫn cần hiểu join, index và hình dạng của query. Nếu không, ORM có thể che giấu các N+1 query chậm hoặc kéo về nhiều dữ liệu hơn mức cần thiết."),
    ("Concurrent requests can still insert duplicates.", "Các request đồng thời vẫn có thể chèn dữ liệu trùng lặp."),
    ("Concurrent requests can still create duplicates unless the database also enforces the rule.", "Các request đồng thời vẫn có thể tạo dữ liệu trùng lặp nếu database không tự thực thi ràng buộc này."),
    ("The process may be alive but unable to serve safely due to initialization or dependency state.", "Process có thể vẫn còn sống nhưng chưa thể phục vụ an toàn do trạng thái khởi tạo hoặc trạng thái dependency."),
    ("Good readiness checks reflect whether the instance can actually handle traffic correctly, not just whether a process exists.", "Readiness check tốt phải phản ánh liệu instance có thực sự xử lý traffic đúng cách hay không, chứ không chỉ kiểm tra xem process có tồn tại hay không."),
    ("Long jobs may still be running when the next schedule starts. Locks, lease files, or queue-based orchestration can prevent harmful overlap.", "Các job dài có thể vẫn đang chạy khi lịch kế tiếp bắt đầu. Lock, lease file hoặc điều phối dựa trên queue có thể ngăn tình trạng chồng lấn gây hại."),
    ("The highest-quality model may still be unacceptable if it is too slow or too expensive.", "Model có chất lượng cao nhất vẫn có thể không chấp nhận được nếu nó quá chậm hoặc quá đắt."),
    ("Closures are useful when returning specialized functions with captured configuration.", "Closure hữu ích khi trả về các hàm chuyên biệt có kèm cấu hình đã được capture."),
    ("Without backpressure, queues and memory usage can grow dangerously.", "Nếu không có backpressure, queue và mức sử dụng bộ nhớ có thể tăng lên một cách nguy hiểm."),
    ("Fast cache is only useful when freshness rules are also correct.", "Cache nhanh chỉ hữu ích khi các quy tắc về độ tươi dữ liệu cũng đúng."),
    ("This is useful when some experience is still better than none during dependency issues.", "Điều này hữu ích khi trong lúc dependency gặp sự cố, có một phần trải nghiệm vẫn tốt hơn là không có gì."),
    ("Because abstraction can hide slow query patterns.", "Bởi vì lớp trừu tượng có thể che giấu các mẫu query chậm."),
    ("Because wiring, contracts, and real dependencies can fail in ways units do not cover.", "Bởi vì wiring, contract và dependency thật có thể hỏng theo những cách mà unit test không bao phủ."),
    ("Because it can reduce overhead and make error handling more manageable.", "Bởi vì nó có thể giảm overhead và giúp việc xử lý lỗi dễ kiểm soát hơn."),
    ("Because too many parallel operations can still overwhelm dependencies or the process itself.", "Bởi vì quá nhiều thao tác song song vẫn có thể làm quá tải dependency hoặc chính process đó."),
    ("Because clients should not always need to provide every optional behavior setting.", "Bởi vì client không phải lúc nào cũng nên phải cung cấp mọi cấu hình hành vi tùy chọn."),
    ("Because they reduce trust in the suite and waste debugging time.", "Bởi vì chúng làm giảm niềm tin vào bộ test và lãng phí thời gian debug."),
    ("Because it expands coverage without duplicating test structure.", "Bởi vì nó mở rộng độ bao phủ mà không cần lặp lại cấu trúc test."),
    ("Because production viability depends on multiple competing constraints.", "Bởi vì khả năng vận hành được trong production phụ thuộc vào nhiều ràng buộc cạnh tranh lẫn nhau."),
    ("Choose a list when items need to change. Choose a tuple when the data should stay fixed after creation.", "Hãy chọn list khi các phần tử cần thay đổi. Hãy chọn tuple khi dữ liệu nên được giữ nguyên sau khi tạo."),
    ("A fast cache is only useful when freshness rules are also correct.", "Cache nhanh chỉ hữu ích khi các quy tắc về độ tươi dữ liệu cũng đúng."),
    ("The pattern stores an event in the same transaction, then a relay publishes it later.", "Pattern này lưu event trong cùng một transaction, sau đó một tiến trình relay sẽ phát hành nó về sau."),
    ("The exact balance depends on business priorities and failure assumptions.", "Sự cân bằng chính xác phụ thuộc vào ưu tiên kinh doanh và các giả định về lỗi."),
    ("The tradeoff is that batching can increase per-request latency.", "Trade-off là batching có thể làm tăng độ trễ của từng request."),
    ("The defined interface and expectations between systems.", "Giao diện và các kỳ vọng đã được định nghĩa giữa các hệ thống."),
    ("Precision answers how many predicted positives were actually correct. Recall answers how many real positives you successfully found. The right balance depends on the business cost of false positives versus false negatives.", "Precision cho biết có bao nhiêu dự đoán dương tính là đúng thật. Recall cho biết bạn tìm ra được bao nhiêu trường hợp dương tính thực tế. Cân bằng phù hợp giữa hai chỉ số này phụ thuộc vào chi phí nghiệp vụ của false positive so với false negative."),
    ("A. The 'best' offline metric model may be too slow or expensive for real product use.", "Model có chỉ số offline 'tốt nhất' vẫn có thể quá chậm hoặc quá đắt cho việc dùng trong sản phẩm thực tế."),
    ("A. The model may look strong on clean demos but fail on messy real queries.", "Model có thể trông rất mạnh trên các bản demo sạch đẹp nhưng lại thất bại trên các truy vấn thực tế lộn xộn."),
    ("A. The action may happen multiple times and create duplicate side effects.", "Hành động đó có thể xảy ra nhiều lần và tạo ra các tác dụng phụ trùng lặp."),
    ("A. ORM-generated queries can still be inefficient or incorrect for the workload.", "Các query do ORM sinh ra vẫn có thể kém hiệu quả hoặc không phù hợp với workload."),
    ("The hard part of caching is not storing values, but keeping them accurate enough for real product behavior.", "Phần khó của caching không phải là lưu giá trị, mà là giữ cho chúng đủ chính xác so với hành vi thực tế của sản phẩm."),
    ("It is useful when syntax requires a statement but the implementation is not ready yet.", "Nó hữu ích khi cú pháp đòi hỏi phải có một câu lệnh nhưng phần triển khai vẫn chưa sẵn sàng."),
    ("It is useful when two or more sequences should be processed in parallel.", "Nó hữu ích khi hai hoặc nhiều sequence cần được xử lý song song."),
    ("It is useful when you need both the removed value and the mutation.", "Nó hữu ích khi bạn cần cả giá trị bị lấy ra lẫn thao tác thay đổi dữ liệu."),
    ("This is one reason dictionaries are a core building block in Python.", "Đây là một trong những lý do dictionary là khối xây dựng cốt lõi trong Python."),
    ("Printing can still be useful at CLI boundaries, but core logic is more flexible when it returns values.", "Việc in ra vẫn có thể hữu ích ở ranh giới CLI, nhưng logic cốt lõi sẽ linh hoạt hơn khi nó trả về giá trị."),
    ("The base case is what stops the recursive chain.", "Base case là thứ chặn chuỗi gọi đệ quy tiếp tục."),
    ("Changes inside nested mutable values can still affect both copies.", "Các thay đổi bên trong những giá trị mutable lồng nhau vẫn có thể ảnh hưởng đến cả hai bản sao."),
    ("It is useful when you need a truly independent structure.", "Nó hữu ích khi bạn cần một cấu trúc thực sự độc lập."),
    ("The extra `s` stands for string.", "Chữ `s` thêm vào là viết tắt của string."),
    ("It is useful when processing large files incrementally.", "Nó hữu ích khi xử lý các file lớn theo từng phần."),
    ("The `finally` block runs whether an exception happened or not.", "Khối `finally` sẽ chạy dù có exception xảy ra hay không."),
    ("This is the foundation of object-oriented programming in Python.", "Đây là nền tảng của lập trình hướng đối tượng trong Python."),
    ("It is useful when behavior is conceptually related to the class but independent of object data.", "Nó hữu ích khi hành vi có liên quan về mặt khái niệm tới class nhưng không phụ thuộc vào dữ liệu của object."),
    ("The request succeeded.", "Request đã thành công."),
    ("The server encountered an internal error.", "Server đã gặp một lỗi nội bộ."),
    ("The returned value is a string unless you convert it.", "Giá trị được trả về là một string trừ khi bạn tự chuyển đổi nó."),
    ("The target value the model is trying to predict.", "Giá trị mục tiêu mà model đang cố dự đoán."),
    ("The proportion of predicted positives that were actually correct.", "Tỷ lệ các dự đoán dương tính thực sự là đúng."),
    ("The proportion of actual positives that the model successfully found.", "Tỷ lệ các trường hợp dương tính thực tế mà model tìm được thành công."),
    ("This is useful when you need both the key and value at the same time.", "Điều này hữu ích khi bạn cần cả key và value cùng lúc."),
    ("This is useful when working with multilingual content.", "Điều này hữu ích khi làm việc với nội dung đa ngôn ngữ."),
    ("The matching `except` handles the failure path when needed.", "Khối `except` tương ứng sẽ xử lý nhánh lỗi khi cần."),
    ("Good exception handling should stay specific rather than hiding everything.", "Xử lý exception tốt nên giữ tính cụ thể thay vì che giấu mọi thứ."),
    ("Because keys differ by environment and should stay secret.", "Bởi vì key khác nhau theo từng môi trường và cần được giữ bí mật."),
    ("This is useful when parsing imperfect payloads or optional fields.", "Điều này hữu ích khi parse các payload chưa hoàn hảo hoặc các trường tùy chọn."),
    ("The recovery strategy depends on the failure class.", "Chiến lược phục hồi phụ thuộc vào loại lỗi gặp phải."),
    ("This is useful when debugging remote failures.", "Điều này hữu ích khi debug các lỗi từ hệ thống ở xa."),
    ("Normalization improves consistency, though denormalization can still be useful in some cases.", "Chuẩn hóa giúp tăng tính nhất quán, dù trong một số trường hợp phi chuẩn hóa vẫn có thể hữu ích."),
    ("However, they do not remove the need to understand SQL behavior.", "Tuy vậy, chúng không loại bỏ nhu cầu phải hiểu hành vi của SQL."),
    ("Because some workflows need to insert-or-update records safely in one logical step.", "Bởi vì một số workflow cần chèn-hoặc-cập-nhật bản ghi một cách an toàn trong một bước logic duy nhất."),
    ("The right loading strategy depends on access patterns.", "Chiến lược tải dữ liệu phù hợp phụ thuộc vào mẫu truy cập."),
    ("Because operators need to know not just what began, but what finished and with what result.", "Bởi vì người vận hành không chỉ cần biết điều gì đã bắt đầu, mà còn cần biết điều gì đã kết thúc và với kết quả ra sao."),
    ("The best loading strategy depends on access patterns.", "Chiến lược tải dữ liệu tốt nhất phụ thuộc vào mẫu truy cập."),
]

WORD_REPLACEMENTS = {
    " items need to change ": " các phần tử cần thay đổi ",
    " data should stay fixed after creation ": " dữ liệu nên giữ nguyên sau khi được tạo ",
    " you need unique values or fast membership checks ": " bạn cần các giá trị duy nhất hoặc cần kiểm tra membership nhanh ",
    " data is naturally key-value based and should be accessed by name or id ": " dữ liệu vốn ở dạng key-value và nên được truy cập theo tên hoặc id ",
    " mutable default arguments ": " tham số mặc định mutable ",
    " dangerous ": " nguy hiểm ",
    " executed directly ": " file được chạy trực tiếp ",
    " imported as a module ": " file được import như một module ",
    " variable number of positional values ": " số lượng giá trị positional thay đổi ",
    " compact way ": " cách viết gọn ",
    " build a list ": " tạo một list ",
    " build a dictionary ": " tạo một dictionary ",
    " optional filtering ": " điều kiện lọc tùy chọn ",
    " key-value mappings ": " các ánh xạ key-value ",
    " fast lookup by key ": " tra cứu nhanh theo key ",
    " values should be treated as fixed and not mutated ": " các giá trị nên được xem là cố định và không bị thay đổi ",
    " repeated membership checks ": " các phép kiểm tra membership lặp lại ",
    " closes the file automatically even if an error occurs ": " tự động đóng file ngay cả khi có lỗi xảy ra ",
    " request validation ": " validation request ",
    " schema validation ": " validation schema ",
    " malformed requests before they spread through the system ": " các request sai cấu trúc trước khi chúng lan ra toàn hệ thống ",
    " opening database connections is expensive and a pool reuses them efficiently ": " việc mở kết nối database là tốn kém và pool sẽ tái sử dụng chúng hiệu quả ",
    " stronger transactional consistency can outweigh distribution benefits ": " tính nhất quán giao dịch mạnh hơn có thể đáng giá hơn lợi ích của việc phân tán ",
    " duplicate messages ": " các message trùng lặp ",
    " retry storm ": " cơn bão retry ",
    " queue lag ": " độ trễ queue ",
    " processing age ": " tuổi xử lý ",
    " process-up ": " process đang chạy ",
    " clean demos ": " các bản demo đẹp ",
    " messy real queries ": " các truy vấn thực tế lộn xộn ",
    " context managers ": " context manager ",
    " a monolith ": " monolith ",
    " monolith ": " monolith ",
    " embeddings ": " embedding ",
    " semantic search ": " tìm kiếm ngữ nghĩa ",
    " retrieval-augmented generation ": " retrieval-augmented generation ",
    " circuit breaker ": " circuit breaker ",
    " configuration loading ": " việc nạp cấu hình ",
    " split code into modules ": " tách code thành các module ",
    " one large file ": " một file lớn ",
    " explicit return types ": " kiểu trả về tường minh ",
    " service functions ": " các hàm service ",
    " parsing input ": " việc parse input ",
    " domain processing ": " xử lý nghiệp vụ ",
    " api handlers ": " các API handler ",
    " non-200 responses ": " các response khác 200 ",
    " repeated expensive reads ": " các lần đọc tốn kém lặp lại ",
    " some staleness ": " một mức độ dữ liệu cũ nhất định ",
    " orm convenience ": " sự tiện lợi của ORM ",
    " sql knowledge ": " kiến thức SQL ",
    " external api failures ": " lỗi từ API bên ngoài ",
    " one query per parent row ": " một query cho mỗi dòng cha ",
    " one shaped query ": " một query được thiết kế phù hợp ",
    " required columns ": " các cột cần thiết ",
    " raw internal exceptions ": " exception nội bộ thô ",
    " global session ": " session toàn cục ",
    " controlled session ": " session được kiểm soát ",
    " because many delivery systems are effectively at-least-once in real operations ": " bởi vì nhiều hệ thống giao nhận trong thực tế vận hành theo kiểu at-least-once ",
    " call ": " lời gọi ",
    " calls ": " các lời gọi ",
    " callable ": " callable ",
    " wraps ": " bọc ",
    " another ": " một ",
    " function ": " hàm ",
    " functions ": " các hàm ",
    " class ": " class ",
    " classes ": " các class ",
    " extend behavior ": " mở rộng hành vi ",
    " remembers ": " ghi nhớ ",
    " variables ": " các biến ",
    " enclosing scope ": " scope bao quanh ",
    " setup ": " khởi tạo ",
    " cleanup ": " dọn dẹp ",
    " block of code ": " khối code ",
    " iterable ": " iterable ",
    " iterator ": " iterator ",
    " yields items ": " trả ra các phần tử ",
    " until exhaustion ": " cho đến khi hết ",
    " lazy processing ": " xử lý lười ",
    " lower memory use ": " giảm sử dụng bộ nhớ ",
    " waiting on i/o ": " chờ I/O ",
    " cpu-bound ": " bị ràng buộc bởi CPU ",
    " i/o-bound ": " bị ràng buộc bởi I/O ",
    " multiple processes ": " nhiều tiến trình ",
    " one thread ": " một luồng ",
    " waiting tasks ": " các tác vụ đang chờ ",
    " efficiently ": " hiệu quả ",
    " scheduler ": " bộ lập lịch ",
    " coroutine ": " coroutine ",
    " execution ": " thực thi ",
    " io readiness ": " trạng thái sẵn sàng I/O ",
    " async programs ": " chương trình async ",
    " awaitables ": " các awaitable ",
    " concurrently ": " đồng thời ",
    " critical section ": " vùng tới hạn ",
    " expensive section ": " vùng tốn kém ",
    " producer ": " producer ",
    " consumer ": " consumer ",
    " decouple ": " tách rời ",
    " pacing ": " nhịp độ ",
    " handoff ": " bàn giao ",
    " malformed requests ": " các request sai cấu trúc ",
    " parent rows ": " các dòng cha ",
    " related rows ": " các dòng liên quan ",
    " rollback ": " rollback ",
    " database writes ": " các lần ghi vào database ",
    " event publication ": " việc phát event ",
    " failing dependency ": " dependency đang lỗi ",
    " dependency ": " dependency ",
    " dependencies ": " các dependency ",
    " retries ": " retry ",
    " retry ": " retry ",
    " fallback ": " fallback ",
    " fallbacks ": " các fallback ",
    " transient ": " tạm thời ",
    " malformed ": " sai cấu trúc ",
    " malformed input ": " input sai cấu trúc ",
    " payload ": " payload ",
    " payloads ": " các payload ",
    " request validation ": " validation request ",
    " schema validation ": " validation schema ",
    " read traffic ": " lưu lượng đọc ",
    " storage usage ": " dung lượng lưu trữ sử dụng ",
    " query patterns ": " các mẫu query ",
    " schema changes ": " các thay đổi schema ",
    " explicit ": " rõ ràng ",
    " repeatable ": " có thể lặp lại ",
    " trackable ": " có thể theo dõi ",
    " liveness ": " liveness ",
    " readiness ": " readiness ",
    " traffic ": " traffic ",
    " logs ": " log ",
    " metrics ": " metrics ",
    " traces ": " traces ",
    " alerts ": " cảnh báo ",
    " free text ": " văn bản tự do ",
    " request id ": " request id ",
    " user id ": " user id ",
    " objective ": " mục tiêu ",
    " indicator ": " chỉ số ",
    " degraded behavior ": " hành vi suy giảm ",
    " unavailable ": " không khả dụng ",
    " configuration concerns ": " các mối quan tâm về cấu hình ",
    " domain behavior ": " hành vi nghiệp vụ ",
    " different reasons ": " những lý do khác nhau ",
    " navigation ": " điều hướng ",
    " ownership ": " quyền sở hữu ",
    " change isolation ": " khả năng cô lập thay đổi ",
    " transport ": " tầng transport ",
    " persistence ": " persistence ",
    " hardcoding ": " hardcode ",
    " internally ": " ở bên trong ",
    " tooling ": " công cụ ",
    " normalized input ": " input đã chuẩn hóa ",
    " branching ": " nhánh xử lý ",
    " ambiguity ": " sự mơ hồ ",
    " service layer ": " tầng service ",
    " business rules ": " các quy tắc nghiệp vụ ",
    " handlers ": " các handler ",
    " required fields ": " các trường bắt buộc ",
    " structure and types ": " cấu trúc và kiểu dữ liệu ",
    " repeated expensive reads ": " các lần đọc tốn kém lặp đi lặp lại ",
    " staleness ": " độ cũ dữ liệu ",
    " generated queries ": " các query được sinh ra ",
    " workload ": " workload ",
    " upstream instability ": " sự bất ổn của upstream ",
    " adapter ": " adapter ",
    " boundary ": " ranh giới ",
    " test doubles ": " test double ",
    " per-row queries ": " các query theo từng dòng ",
    " round trips ": " các vòng round trip ",
    " query overhead ": " overhead của query ",
    " loading strategy ": " chiến lược tải dữ liệu ",
    " access pattern ": " mẫu truy cập ",
    " extra columns ": " các cột dư thừa ",
    " transfer ": " truyền tải ",
    " parsing ": " parse ",
    " memory cost ": " chi phí bộ nhớ ",
    " mutable ": " có thể thay đổi ",
    " derived objects ": " object phát sinh ",
    " in-place ": " tại chỗ ",
    " stale ": " cũ ",
    " unexpectedly modified ": " bị sửa đổi ngoài dự kiến ",
    " internal exceptions ": " exception nội bộ ",
    " client-facing ": " hướng tới client ",
    " global session ": " session toàn cục ",
    " unit of work ": " đơn vị công việc ",
    " invalidation ": " invalidation ",
    " freshness ": " độ tươi mới ",
    " correctness ": " tính đúng đắn ",
    " wraps another function or class to extend behavior": "bọc một hàm hoặc class khác để mở rộng hành vi",
    " remembers variables from its enclosing scope": "ghi nhớ các biến từ scope bao quanh",
    " guarantee setup and cleanup around a block of code": "đảm bảo việc khởi tạo và dọn dẹp quanh một khối code",
    " support lazy processing and lower memory use": "hỗ trợ xử lý lười và giảm sử dụng bộ nhớ",
    " spend a lot of time waiting on i/o": "dành nhiều thời gian để chờ I/O",
    " can benefit from multiple processes": "có thể hưởng lợi từ nhiều tiến trình",
    " manage many waiting tasks efficiently": "quản lý nhiều tác vụ đang chờ một cách hiệu quả",
    " fail fast ": " thất bại sớm ",
    " configuration ": " cấu hình ",
    " business logic ": " logic nghiệp vụ ",
    " domain ": " domain ",
    " environment ": " môi trường ",
    " environments ": " các môi trường ",
    " service ": " service ",
    " services ": " các service ",
    " request ": " request ",
    " requests ": " các request ",
    " response ": " response ",
    " responses ": " các response ",
    " payload ": " payload ",
    " payloads ": " các payload ",
    " timeout ": " timeout ",
    " timeouts ": " các timeout ",
    " retries ": " retry ",
    " retry ": " retry ",
    " caching ": " caching ",
    " queue ": " queue ",
    " queues ": " các queue ",
    " worker ": " worker ",
    " workers ": " các worker ",
    " model ": " model ",
    " models ": " các model ",
    " evaluation ": " đánh giá ",
    " training ": " huấn luyện ",
    " deployment ": " triển khai ",
    " production ": " production ",
}


def translate_text(text: str) -> str:
    if not text:
        return text

    out = text.strip()

    for source, target in REPLACEMENTS:
        if out == source:
            return target

    patterns = [
        (r"^Choose a (.+) when (.+)\. Choose a (.+) when (.+)\.$", r"Hãy chọn \1 khi \2. Hãy chọn \3 khi \4."),
        (r"^Use a (.+) when you need (.+)\.$", r"Dùng \1 khi bạn cần \2."),
        (r"^When you need to (.+)\.$", r"Khi bạn cần \1."),
        (r"^When data is naturally (.+)\.$", r"Khi dữ liệu vốn mang tính \1."),
        (r"^To run code only when (.+)\.$", r"Để chỉ chạy code khi \1."),
        (r"^To store (.+)\.$", r"Để lưu \1."),
        (r"^It returns (.+)\.$", r"Nó trả về \1."),
        (r"^It ensures (.+)\.$", r"Nó đảm bảo \1."),
        (r"^It keeps (.+)\.$", r"Nó giữ \1."),
        (r"^It allows (.+)\.$", r"Nó cho phép \1."),
        (r"^It helps (.+)\.$", r"Nó giúp \1."),
        (r"^It limits (.+)\.$", r"Nó giới hạn \1."),
        (r"^They guarantee (.+)\.$", r"Chúng đảm bảo \1."),
        (r"^They support (.+)\.$", r"Chúng hỗ trợ \1."),
        (r"^They make (.+)\.$", r"Chúng làm cho \1."),
        (r"^This helps (.+)\.$", r"Điều này giúp \1."),
        (r"^This improves (.+)\.$", r"Điều này cải thiện \1."),
        (r"^This reduces (.+)\.$", r"Điều này giảm \1."),
        (r"^This matters (.+)\.$", r"Điều này quan trọng \1."),
        (r"^Because (.+)\.$", r"Bởi vì \1."),
        (r"^What is the difference between (.+) and (.+)\?$", r"Sự khác nhau giữa \1 và \2 là gì?"),
        (r"^What is the (.+)\?$", r"\1 là gì?"),
        (r"^What is a (.+)\?$", r"\1 là gì?"),
        (r"^What is an (.+)\?$", r"\1 là gì?"),
        (r"^What does (.+) help with\?$", r"\1 giúp gì?"),
        (r"^What does (.+) return\?$", r"\1 trả về gì?"),
        (r"^What does (.+) mean\?$", r"\1 có nghĩa là gì?"),
        (r"^What does (.+) usually mean\?$", r"\1 thường có nghĩa là gì?"),
        (r"^What does (.+) do on (.+)\?$", r"\1 làm gì trên \2?"),
        (r"^What does (.+) do in (.+)\?$", r"\1 dùng để làm gì trong \2?"),
        (r"^What is (.+) in practice\?$", r"Trong thực tế, \1 là gì?"),
        (r"^What is (.+)\?$", r"\1 là gì?"),
        (r"^When is (.+) a better choice than (.+)\?$", r"Khi nào \1 là lựa chọn tốt hơn \2?"),
        (r"^When would you use (.+) instead of (.+)\?$", r"Khi nào bạn sẽ dùng \1 thay vì \2?"),
        (r"^What problem do (.+) solve\?$", r"\1 giải quyết vấn đề gì?"),
        (r"^What problem does (.+) solve\?$", r"\1 giải quyết vấn đề gì?"),
        (r"^What problem does (.+) solve in (.+)\?$", r"\1 giải quyết vấn đề gì trong \2?"),
        (r"^What should good (.+) include\?$", r"\1 tốt nên bao gồm những gì?"),
        (r"^Which is usually better for (.+): (.+) or (.+)\?$", r"Đối với \1, cách nào thường tốt hơn: \2 hay \3?"),
        (r"^Which is usually more memory efficient for (.+): (.+) or (.+)\?$", r"Đối với \1, cách nào thường tiết kiệm bộ nhớ hơn: \2 hay \3?"),
        (r"^Which is usually safer (.+): (.+) or (.+)\?$", r"Trong trường hợp \1, cách nào thường an toàn hơn: \2 hay \3?"),
        (r"^Which approach is usually better for (.+)\?$", r"Cách tiếp cận nào thường tốt hơn cho \1?"),
        (r"^Which is often the first optimization target in (.+)\?$", r"Trong \1, mục tiêu tối ưu đầu tiên thường là gì?"),
        (r"^What is the main optimization problem in (.+)\?$", r"Vấn đề tối ưu chính trong \1 là gì?"),
        (r"^What is the trap in (.+)\?$", r"Bẫy nằm ở đâu khi \1?"),
        (r"^The trap in (.+) is what\?$", r"Bẫy của việc \1 là gì?"),
        (r"^The trap in (.+)\?$", r"Bẫy của việc \1 là gì?"),
        (r"^The main use of (.+)\?$", r"Công dụng chính của \1 là gì?"),
        (r"^The main optimization problem in (.+) is what\?$", r"Vấn đề tối ưu chính trong \1 là gì?"),
        (r"^The likely bottleneck in (.+)\?$", r"Nút thắt cổ chai có khả năng nằm ở đâu khi \1?"),
        (r"^The average lookup cost for (.+)\?$", r"Chi phí tra cứu trung bình cho \1 là gì?"),
        (r"^The goal of (.+)\?$", r"Mục tiêu của \1 là gì?"),
        (r"^The value of (.+)\?$", r"Giá trị của \1 là gì?"),
        (r"^The cost of (.+)\?$", r"Cái giá phải trả của việc \1 là gì?"),
        (r"^The tradeoff between (.+) and (.+)\?$", r"Trade-off giữa \1 và \2 là gì?"),
        (r"^Why use (.+)\?$", r"Vì sao dùng \1?"),
        (r"^Why add (.+)\?$", r"Vì sao thêm \1?"),
        (r"^Why do (.+) matter\?$", r"Vì sao \1 lại quan trọng?"),
        (r"^What does (.+) do in a function definition\?$", r"\1 dùng để làm gì trong định nghĩa hàm?"),
        (r"^What does (.+) do inside a loop\?$", r"\1 dùng để làm gì trong vòng lặp?"),
        (r"^What does (.+) provide in a loop\?$", r"\1 cung cấp gì trong vòng lặp?"),
        (r"^What does (.+) produce\?$", r"\1 tạo ra gì?"),
        (r"^What does (.+) do\?$", r"\1 dùng để làm gì?"),
        (r"^When should you use (.+)\?$", r"Khi nào nên dùng \1?"),
        (r"^When should (.+)\?$", r"Khi nào nên \1?"),
        (r"^When is (.+)\?$", r"Khi nào \1?"),
        (r"^Why should (.+)\?$", r"Vì sao nên \1?"),
        (r"^Why is it okay to (.+) in an interview question\?$", r"Vì sao việc \1 trong câu hỏi phỏng vấn là chấp nhận được?"),
        (r"^Why is it good to say (.+) in an interview\?$", r"Vì sao nên nói \1 trong một buổi phỏng vấn?"),
        (r"^Why is (.+) used\?$", r"Vì sao dùng \1?"),
        (r"^Why is (.+) useful when (.+)\?$", r"Vì sao \1 lại hữu ích khi \2?"),
        (r"^Why is (.+) useful\?$", r"Vì sao \1 lại hữu ích?"),
        (r"^Why is (.+) dangerous\?$", r"Vì sao \1 lại nguy hiểm?"),
        (r"^Why is (.+)\?$", r"Vì sao \1?"),
        (r"^Why are (.+) dangerous\?$", r"Vì sao \1 lại nguy hiểm?"),
        (r"^Why are (.+)\?$", r"Vì sao \1?"),
        (r"^Why does (.+) matter\?$", r"Vì sao \1 lại quan trọng?"),
        (r"^Why does (.+)\?$", r"Vì sao \1?"),
        (r"^Why can (.+) still require (.+)\?$", r"Vì sao \1 vẫn đòi hỏi \2?"),
        (r"^Why can (.+) still be valuable even if (.+)\?$", r"Vì sao \1 vẫn có giá trị ngay cả khi \2?"),
        (r"^Why can (.+) still be misleading\?$", r"Vì sao \1 vẫn có thể gây hiểu lầm?"),
        (r"^Why can (.+) still be a strong design choice\?$", r"Vì sao \1 vẫn có thể là một lựa chọn thiết kế mạnh?"),
        (r"^Why can (.+) still be a good design\?$", r"Vì sao \1 vẫn có thể là một thiết kế tốt?"),
        (r"^Why can (.+) be powerful and dangerous at the same time\?$", r"Vì sao \1 vừa mạnh mẽ vừa nguy hiểm cùng lúc?"),
        (r"^Why can (.+)\?$", r"Vì sao \1 có thể xảy ra?"),
        (r"^Why must (.+) still be evaluated carefully\?$", r"Vì sao \1 vẫn phải được đánh giá cẩn thận?"),
        (r"^Why must (.+)\?$", r"Vì sao \1 là bắt buộc?"),
        (r"^What makes (.+)\?$", r"Điều gì làm cho \1?"),
    ]

    for pattern, replacement in patterns:
        if re.match(pattern, out):
            out = re.sub(pattern, replacement, out)
            break

    for source, target in REPLACEMENTS:
        out = out.replace(source, target)

    out = f" {out} "
    for source, target in WORD_REPLACEMENTS.items():
        out = out.replace(source, target)

    out = out.strip()
    out = re.sub(r"\s+", " ", out)
    out = out.replace("A. ", "")
    out = out.replace("A ", "")
    if out and out[0].islower():
        out = out[0].upper() + out[1:]
    return out


def translate_item(item: dict) -> dict:
    translated = dict(item)
    translated["category_vi"] = CATEGORY_MAP.get(item.get("category", ""), item.get("category", ""))
    translated["question_en"] = item.get("question", "")
    translated["question_vi"] = item.get("question_vi") or translate_text(item.get("question", ""))
    translated["question"] = translated["question_vi"]
    translated["correct_answer_en"] = item.get("correct_answer", "")
    translated["correct_answer_vi"] = translate_text(item.get("correct_answer", ""))
    translated["correct_answer"] = translated["correct_answer_vi"]
    translated["explanation_en"] = item.get("explanation", "")
    translated["explanation_vi"] = translate_text(item.get("explanation", ""))
    translated["explanation"] = translated["explanation_vi"]

    if "level" in translated:
        translated["level_en"] = translated["level"]
        translated["level"] = LEVEL_MAP.get(translated["level"], translated["level"])

    if isinstance(item.get("options"), list):
        translated["options_en"] = item["options"]
        translated["options_vi"] = [translate_text(option) for option in item["options"]]
        translated["options"] = translated["options_vi"]

    if isinstance(item.get("compare"), list):
        translated["compare_en"] = item["compare"]
        translated["compare_vi"] = [translate_text(entry) for entry in item["compare"]]
        translated["compare"] = translated["compare_vi"]

    if "intent" in translated and translated["intent"]:
        translated["intent_en"] = translated["intent"]
        translated["intent_vi"] = translate_text(translated["intent"])
        translated["intent"] = translated["intent_vi"]

    return translated


def translate_file(path: Path) -> None:
    payload = json.loads(path.read_text(encoding="utf-8"))
    translated = dict(payload)

    translated["title_en"] = payload.get("title", "")
    translated["title"] = TITLE_MAP.get(payload.get("title", ""), translate_text(payload.get("title", "")))
    translated["subtitle_en"] = payload.get("subtitle", "")
    translated["subtitle"] = SUBTITLE_MAP.get(payload.get("subtitle", ""), translate_text(payload.get("subtitle", "")))

    if "level" in translated:
        translated["level_en"] = translated["level"]
        translated["level"] = LEVEL_MAP.get(translated["level"], translated["level"])

    translated["questions"] = [translate_item(item) for item in payload.get("questions", [])]

    out_path = path.with_name(path.stem + "-vi.json")
    out_path.write_text(json.dumps(translated, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {out_path.relative_to(ROOT)}")


def main() -> None:
    for path in QUESTION_FILES:
        translate_file(path)


if __name__ == "__main__":
    main()
